INSERT INTO tblTeam (teamAbbr, teamLocation, teamName) VALUES 
('MIL', 'Milwaukee', 'Bucks'),
('TOR', 'Toronto', 'Raptors'),
('BOS', 'Boston', 'Celtics'),
('MIA', 'Miami', 'Heat'),
('IND', 'Indiana', 'Pacers'),
('PHI', 'Philadelphia', '76ers'),
('BRK', 'Brooklyn', 'Nets'),
('ORL', 'Orlando', 'Magic'),
('WAS', 'Washington', 'Wizards'),
('CHO', 'Charlotte', 'Hornets'),
('CHI', 'Chicago', 'Bulls'),
('NYK', 'New York', 'Knicks'),
('DET', 'Detroit', 'Pistons'),
('ATL', 'Atlanta', 'Hawks'),
('CLE', 'Cleveland', 'Cavaliers'),
('LAL', 'Los Angeles', 'Lakers'),
('LAC', 'Los Angeles', 'Clippers'),
('DEN', 'Denver', 'Nuggets'),
('UTA', 'Utah', 'Jazz'),
('OKC', 'Oklahoma City', 'Thunder'),
('HOU', 'Houston', 'Rockets'),
('DAL', 'Dallas', 'Mavericks'),
('MEM', 'Memphis', 'Grizzlies'),
('POR', 'Portland', 'Trailblazers'),
('NOP', 'New Orleans', 'Pelicans'),
('SAC', 'Sacramento', 'Kings'),
('SAS', 'San Antonio', 'Spurs'),
('PHO', 'Phoenix', 'Suns'),
('MIN', 'Minnesota', 'Timberwolves'),
('GSW', 'Golden State', 'Warriors')
;